# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.0].define(version: 2025_05_22_061800) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "pg_catalog.plpgsql"

  create_table "annual_reports", force: :cascade do |t|
    t.date "from", null: false, comment: "When the report starts"
    t.date "until", null: false, comment: "When the report ends"
    t.integer "year", null: false, comment: "The year of the report, only one report per year is allowed"
    t.integer "number_of_disbursements", default: 0, null: false, comment: "Total number of disbursements in the period"
    t.float "amount_disbursed_to_merchants", default: 0.0, null: false, comment: "Total amount disbursed to merchants in the period"
    t.float "amount_of_orders_fee", default: 0.0, null: false, comment: "Total amount of orders fee in the period"
    t.integer "number_of_monthly_fees_charged", default: 0, null: false, comment: "How many monthly fees were charged in the period"
    t.float "amount_of_monthly_fees_charged", default: 0.0, null: false, comment: "Total amount of monthly fees in the period"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["from"], name: "index_annual_reports_on_from"
    t.index ["until"], name: "index_annual_reports_on_until"
    t.index ["year"], name: "index_annual_reports_on_year", unique: true
  end

  create_table "disbursements", force: :cascade do |t|
    t.bigint "merchant_id", null: false, comment: "Merchant that the disbursement belongs to"
    t.date "disbursement_date", null: false, comment: "The date of the disbursement"
    t.float "total_commission", default: 0.0, null: false, comment: "The sum of the commission fees of all the orders"
    t.float "total_amount", default: 0.0, null: false, comment: "The total amount of the disbursement, it is the sum of all the orders amount"
    t.float "disbursed_amount", default: 0.0, null: false, comment: "The amount that the merchant will receive after the commission fees are deducted"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["merchant_id", "disbursement_date"], name: "index_disbursements_on_merchant_id_and_disbursement_date", unique: true
  end

  create_table "merchants", force: :cascade do |t|
    t.string "email", null: false, comment: "Merchant email"
    t.string "reference", null: false, comment: "Merchant reference"
    t.date "live_on", null: false, comment: "When the merchant start the business with sequra"
    t.integer "disbursement_frequency", null: false, comment: "The frequency of the disbursement"
    t.float "minimum_monthly_fee", null: false, comment: "The minimum monthly fee that the merchant has to reach"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "monthly_fee_compliances", force: :cascade do |t|
    t.bigint "merchant_id", null: false, comment: "Merchant that the fee compliance belongs to"
    t.date "period", null: false, comment: "The date of the first day of the month which the fee compliance is for"
    t.float "minimum_monthly_fee", default: 0.0, null: false, comment: "The minimum monthly fee for the merchant"
    t.float "total_commissions_generated", default: 0.0, null: false, comment: "The total commissions generated by the merchant in the month"
    t.float "missing_amount", default: 0.0, null: false, comment: "The amount that is missing to reach the minimum monthly fee"
    t.boolean "fee_due", default: false, null: false, comment: "Whether the fee is due or not"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.float "total_amount", default: 0.0, null: false, comment: "The total amount of the orders generated by the merchant in the month"
    t.index ["merchant_id", "period"], name: "index_monthly_fee_compliances_on_merchant_id_and_period", unique: true, comment: "Only one fee compliance per merchant per month"
  end

  create_table "orders", force: :cascade do |t|
    t.float "amount", null: false, comment: "The amount of the order"
    t.date "order_received_at", null: false, comment: "The date of the order"
    t.bigint "merchant_id", null: false, comment: "Merchant that the order belongs to"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "disbursement_id", comment: "The disbursement that the order belongs to, can be null if the order is not disbursed yet"
    t.bigint "monthly_fee_compliance_id", comment: "The fee compliance that the order belongs to, can be null if the order has not been related to a fee compliance"
    t.index ["disbursement_id"], name: "index_orders_on_disbursement_id"
    t.index ["merchant_id"], name: "index_orders_on_merchant_id"
    t.index ["monthly_fee_compliance_id"], name: "index_orders_on_monthly_fee_compliance_id"
    t.index ["order_received_at"], name: "index_orders_on_order_received_at"
  end

  add_foreign_key "disbursements", "merchants"
  add_foreign_key "monthly_fee_compliances", "merchants"
  add_foreign_key "orders", "disbursements"
  add_foreign_key "orders", "merchants"
  add_foreign_key "orders", "monthly_fee_compliances"
end
