class CreateFeeComplianceTable < ActiveRecord::Migration[8.0]
  def change
    create_table :monthly_fee_compliances do |t|
      t.references :merchant, null: false, foreign_key: true, index: false, comment: "Merchant that the fee compliance belongs to"

      t.date :period, null: false, comment: "The date of the first day of the month which the fee compliance is for"
      t.float :minimum_monthly_fee, null: false, default: 0.0, comment: "The minimum monthly fee for the merchant"
      t.float :total_commissions_generated, null: false, default: 0.0, comment: "The total commissions generated by the merchant in the month"
      t.float :missing_amount, null: false, default: 0.0, comment: "The amount that is missing to reach the minimum monthly fee"
      t.boolean :fee_due, null: false, default: false, comment: "Whether the fee is due or not"

      t.timestamps
    end

    add_index :monthly_fee_compliances, %i[merchant_id period], unique: true, comment: "Only one fee compliance per merchant per month"

    add_reference :disbursements, :monthly_fee_compliance, null: true, foreign_key: true, comment: "The fee compliance that the disbursement belongs to, can be null if the disbursement is not related to a fee compliance"
    add_reference :orders, :monthly_fee_compliance, null: true, foreign_key: true, comment: "The fee compliance that the order belongs to, can be null if the order has not been related to a fee compliance"
  end
end
