class ModifyFeeComplianceTable < ActiveRecord::Migration[8.0]
  def change
    change_table :monthly_fee_compliances do |t|
      t.float :total_amount, null: false, default: 0.0, comment: "The total amount of the orders generated by the merchant in the month"
    end

    remove_reference :disbursements, :monthly_fee_compliance
  end
end
